# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 09:18
from __future__ import unicode_literals

import base_map.models.shapes
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('place_type', models.CharField(choices=[(b'church', b'Church'), (b'mosque', b'Mosque'), (b'school', b'School'), (b'bar', b'Bar'), (b'shop', b'Shop'), (b'hospital', b'Hospital'), (b'bridge', b'Bridge'), (b'water', b'Water'), (b'sanitation', b'Sanitation'), (b'community', b'Community'), (b'entrance', b'Entrance'), (b'other', b'Other')], max_length=50)),
                ('date_added', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['place_type', 'name'],
                'db_table': 'watsan_landmark',
            },
            bases=(base_map.models.shapes.ShapeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Manhole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'watsan_manhole',
            },
        ),
        migrations.CreateModel(
            name='NewEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('hash_string', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('transfered', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('org_type', models.CharField(choices=[(b'CBO', b'CBO'), (b'NGO', b'NGO'), (b'school', b'School'), (b'private', b'Private')], max_length=10)),
            ],
            options={
                'db_table': 'watsan_organization',
                'permissions': (('access_watsan', 'Can access watsan portal'),),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
            ],
            options={
                'db_table': 'watsan_project',
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('road_type', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'watsan_road',
            },
            bases=(base_map.models.shapes.ShapeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('search_engine', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'watsan_searchresult',
            },
            bases=(base_map.models.shapes.ShapeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SewerLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'watsan_sewerline',
            },
            bases=(base_map.models.shapes.ShapeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('saved', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('color', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watsan_sites',
            },
            bases=(base_map.models.shapes.ShapeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'watsan_village',
            },
            bases=(base_map.models.shapes.ShapeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WaterLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'watsan_waterline',
            },
            bases=(base_map.models.shapes.ShapeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WatsanUserMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(max_length=350)),
                ('question_2', models.CharField(max_length=350)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watsan.Organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watsan_usermeta',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='sites',
            field=models.ManyToManyField(to='watsan.Site'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
