# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 14:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('watsan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 12, 14, 55, 24, 986323, tzinfo=utc)),
        ),
    ]
